name = "simplerauth-github"
compatibility_date = "2025-06-18"
route.custom_domain = true
route.pattern = "gh.simplerauth.com"
main="main.ts"

[[durable_objects.bindings]]
name = "UserDO"
class_name = "UserDO"

[[migrations]]
new_sqlite_classes = ["UserDO"]
tag = "v1"